app:
  clients:
    hostname: 10.166.176.110
    scheme: http
    httpPort: 9200
    containerPort: 9200
    transportPort: 9300
  elastic:
    imageUrl: docker.elastic.co/elasticsearch/elasticsearch
    version: 6.2.1
    credentialUsername: elastic
    credentialPassword: changeme
  index:
    name: ga_day_index-0907,ga_day_index-0908
    type: ga_index_type
    shard: 2
    replica: 1
    from: 0
    size: 5
    timeout: 60 

  mourya:
    hive:
      connectionURL: jdbc:hive2://localhost:10000/default;principal=hive/localhost@ATHENA.MIT.EDU
      username: mourya
      password: password
    kerberos:
      keyTabLocation: ~/Security/mourya.keytab
      krb5Location: ~/krb5.conf
    priniciple: mourya@ATHENA.MIT.EDU