app:
  clients:
    hostname: 10.166.176.110
    scheme: http
    httpPort: 9200
    containerPort: 9200
    transportPort: 9300
  elastic:
    imageUrl: docker.elastic.co/elasticsearch/elasticsearch
    version: 6.2.1
    credentialUsername: elastic
    credentialPassword: changeme
  index:
    name: kodcu
    type: tutorial
    shard: 2
    replica: 1
    from: 0
    size: 5
    timeout: 60 
 
  